using System;
public enum EPlayerButtonType2
{
	E_VIEW_TALENTS,
	E_VIEW_ITEMS,
    E_ADD_BOT_PILOT,
    E_ADD_BOT_SCI,
    E_ADD_BOT_WEAP,
    E_ADD_BOT_ENG,
    E_CHANGE_TO_PILOT,
	E_CHANGE_TO_SCI,
	E_CHANGE_TO_WEAP,
	E_CHANGE_TO_ENG,
	E_ADD_FRIEND,
	E_REMOVE_BOT,
	E_KICK,
	E_MUTE
}
